# Generated by Django 2.2 on 2019-05-02 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_career_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='career',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='career',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8),
        ),
    ]
