# Generated by Django 2.2 on 2019-05-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_careerresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='resources',
            field=models.ManyToManyField(through='game.CareerResource', to='game.Resource'),
        ),
        migrations.AlterField(
            model_name='careerresource',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Career'),
        ),
        migrations.AlterField(
            model_name='careerresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Resource'),
        ),
    ]
