# Generated by Django 2.2 on 2019-05-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190504_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Career')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.MenuItem')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
