# Generated by Django 2.2 on 2019-05-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_careermenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='menu_items',
            field=models.ManyToManyField(through='game.CareerMenuItem', to='game.MenuItem'),
        ),
    ]
