# Generated by Django 2.2 on 2019-05-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_career_menu_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Career')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Equipment')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='career',
            name='equipment',
            field=models.ManyToManyField(through='game.CareerEquipment', to='game.Equipment'),
        ),
    ]
