# Generated by Django 2.2 on 2019-05-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20190504_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.MenuItem')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Resource')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='resources',
            field=models.ManyToManyField(through='game.MenuItemResource', to='game.Resource'),
        ),
    ]
