# Generated by Django 2.2 on 2019-05-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20190505_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='unit',
            field=models.CharField(blank=True, default='pound', max_length=100),
        ),
    ]
