# Generated by Django 2.2 on 2019-05-06 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_resource_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Equipment')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.MenuItem')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='equipment',
            field=models.ManyToManyField(through='game.MenuItemEquipment', to='game.Equipment'),
        ),
    ]
