# Generated by Django 2.2 on 2019-05-12 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20190506_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careermenuitem',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_menu_items', to='game.Career'),
        ),
        migrations.AlterField(
            model_name='menuitemresource',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_resources', to='game.MenuItem'),
        ),
    ]
