# Generated by Django 2.2 on 2019-05-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20190512_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=8),
        ),
        migrations.AlterField(
            model_name='careerequipment',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_equipment', to='game.Career'),
        ),
        migrations.AlterField(
            model_name='careerresource',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_resources', to='game.Career'),
        ),
    ]
