# Generated by Django 2.2 on 2019-05-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20190521_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='location',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Location'),
        ),
        migrations.AlterField(
            model_name='career',
            name='truck',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Truck'),
        ),
    ]
