# Generated by Django 2.2 on 2019-05-31 17:05

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20190528_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=2),
        ),
        migrations.AddField(
            model_name='careermenuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='keywords',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='location',
            name='sentiment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='day',
            name='dawn_condition',
            field=models.CharField(blank=True, choices=[('sunny', 'sunny'), ('cloudy', 'cloudy'), ('rainy', 'rainy'), ('stormy', 'stormy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='day',
            name='dusk_condition',
            field=models.CharField(blank=True, choices=[('sunny', 'sunny'), ('cloudy', 'cloudy'), ('rainy', 'rainy'), ('stormy', 'stormy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='day',
            name='headline',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='day',
            name='max_temp',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='min_temp',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='noon_condition',
            field=models.CharField(blank=True, choices=[('sunny', 'sunny'), ('cloudy', 'cloudy'), ('rainy', 'rainy'), ('stormy', 'stormy')], max_length=50),
        ),
    ]
