# Generated by Django 2.2 on 2019-05-31 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20190531_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='location',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='popularity',
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('polarity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Location')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.MenuItem')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
