# Generated by Django 2.2 on 2019-06-02 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20190531_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careermenuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('result', models.CharField(choices=[('passed', 'passed'), ('rejected', 'rejected'), ('purchased', 'purchased')], max_length=50)),
                ('review', models.CharField(choices=[('cheap', 'cheap'), ('expensive', 'expensive'), ('tasteful', 'tasteful'), ('distasteful', 'distasteful'), ('fast', 'fast'), ('slow', 'slow')], max_length=50, null=True)),
                ('minute_of_day', models.PositiveSmallIntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Day')),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.MenuItem')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
