# Generated by Django 2.2 on 2019-06-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20190602_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
